### ISSUE TITLE
some bug after i check it

### ISSUE THREAD

**Issue by Dhanamerdeka** [Riczap/The-Gatherer#1]
idk why, but there's some kind of bug on [requirements.txt](https://github.com/WanderingEye0/The-Gatherer/blob/main/requirements.txt) i think numpy is one of them... so i just now install all plugin manually....

and can you somehow train the data? can you explain it how to train the data?
some "furniture" beside mob tent is seen as a rock....

**Comment by Riczap** [comment]
Hi, sorry I hadn't checked my socials.
Installing the requirement's with pip should work fine at the moment, just make sure that you are running the command while being in the correct path in the command prompt.
The Yolov5 model that I trained is really just a demo to test that the bot works, it's really time consuming to train the models, so anyone can train their own and just run it with the bot's code.
